# Generated by Django 4.2.13 on 2024-06-10 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movieblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='comment',
            name='description',
            field=models.TextField(default=' '),
        ),
    ]
