# Generated by Django 4.2.13 on 2024-06-10 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movieblog', '0003_commentmodel_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmFilesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Имя файла')),
                ('file', models.FileField(upload_to='film_files/')),
                ('code', models.IntegerField(default=0, unique=True, verbose_name='Код файла')),
                ('download_count', models.IntegerField(default=0, verbose_name='Скачиваний')),
                ('description', models.TextField(default=' ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('New', 'Новые'), ('Favorites', 'Избранное'), ('Watching', 'Смотрю'), ('Viewed', 'Посмотрено')], default='New', max_length=50)),
                ('rating', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=50)),
            ],
            options={
                'verbose_name': 'Файл фильма',
                'verbose_name_plural': 'Файлы фильмов',
            },
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
        migrations.DeleteModel(
            name='Film',
        ),
    ]
