# Generated by Django 4.2.13 on 2024-06-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieblog', '0004_filmfilesmodel_delete_commentmodel_delete_film'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('chat_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Фамилия')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Зарегистрирован')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последняя активность')),
            ],
            options={
                'verbose_name': 'Пользователь сайта',
                'verbose_name_plural': 'Пользователи сайта',
                'ordering': ['-updated'],
            },
        ),
    ]
