# Generated by Django 4.2.13 on 2024-06-10 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieblog', '0005_usermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
