# Generated by Django 4.2.13 on 2024-06-10 12:49

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movieblog', '0006_delete_usermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(verbose_name='Альт. заголовок')),
                ('description', models.CharField(blank=True, max_length=350, verbose_name='Описание')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='movieblog.categorymodel', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Категория фильма',
                'verbose_name_plural': 'Категории фильмов',
                'unique_together': {('parent', 'slug')},
            },
        ),
    ]
