# Generated by Django 4.2.13 on 2024-06-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieblog', '0007_categorymodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorymodel',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
