# Generated by Django 4.2.13 on 2024-06-10 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movieblog', '0008_alter_categorymodel_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmfilesmodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='filmfilesmodel',
            name='description',
        ),
        migrations.RemoveField(
            model_name='filmfilesmodel',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='filmfilesmodel',
            name='status',
        ),
        migrations.CreateModel(
            name='FilmModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Альт. название')),
                ('image', models.ImageField(default='default/not_found.png', upload_to='film/%Y/%m/%d', verbose_name='Постер')),
                ('rating', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=100)),
                ('full_body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Содержимое поста')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Опубликовано')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('status', models.CharField(choices=[('Избранное', 'Favorites'), ('Буду смотреть', 'Wishlist'), ('Посмотрено', 'Watchced'), ('Опубликованное', 'Published')], default='Опубликованное', max_length=100, verbose_name='Статус')),
                ('views', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('category', mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='film', to='movieblog.categorymodel', verbose_name='Категория')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film', to=settings.AUTH_USER_MODEL, verbose_name='Режиссер')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['-publish'],
                'indexes': [models.Index(fields=['-publish'], name='movieblog_f_publish_596d66_idx')],
            },
        ),
    ]
