# Generated by Django 4.2.13 on 2024-06-10 15:41

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movieblog', '0009_remove_filmfilesmodel_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmmodel',
            name='director',
            field=models.CharField(max_length=200, verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='full_body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Основная информация'),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='rating',
            field=models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default='0', max_length=100, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='status',
            field=models.CharField(choices=[('Избранное', 'Избранное'), ('Буду смотреть', 'Буду смотреть'), ('Посмотрено', 'Посмотрено'), ('Опубликованное', 'Опубликованное')], default='Опубликованное', max_length=100, verbose_name='Статус'),
        ),
    ]
