# Generated by Django 4.2.13 on 2024-06-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movieblog', '0012_filmmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmmodel',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='film', to='movieblog.filmfilesmodel', verbose_name='Файл'),
        ),
    ]
