# Generated by Django 4.2.13 on 2024-06-11 14:42

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('movieblog', '0013_filmmodel_file'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='filmmodel',
            managers=[
                ('film_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
