# Generated by Django 5.0.6 on 2024-06-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movieblog", "0014_alter_filmmodel_managers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filmmodel",
            options={},
        ),
        migrations.AlterModelManagers(
            name="filmmodel",
            managers=[],
        ),
        migrations.RemoveIndex(
            model_name="filmmodel",
            name="movieblog_f_publish_596d66_idx",
        ),
        migrations.RemoveField(
            model_name="filmmodel",
            name="file",
        ),
        migrations.RemoveField(
            model_name="filmmodel",
            name="tags",
        ),
        migrations.AlterField(
            model_name="filmmodel",
            name="views",
            field=models.IntegerField(default=0, verbose_name="Просмотры"),
        ),
    ]
