# Generated by Django 5.0.6 on 2024-07-01 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieblog', '0020_alter_filmmodel_rating_alter_ratemodel_rate_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFilmList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_type', models.CharField(choices=[('izbrannoe', 'Избранное'), ('posmotreno', 'Просмотренное'), ('budu-smotret', 'Буду смотреть')], max_length=20)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_lists', to='movieblog.filmmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film_lists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'film', 'list_type')},
            },
        ),
    ]
