# Generated by Django 5.0.6 on 2024-07-08 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("U", "не выбран"),
                            ("M", "мужской"),
                            ("F", "женский"),
                        ],
                        default="U",
                        max_length=1,
                        verbose_name="Пол",
                    ),
                ),
                (
                    "dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата рождения"
                    ),
                ),
                (
                    "user_avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="user/avatars/",
                        verbose_name="Аватар пользователя",
                    ),
                ),
                (
                    "show_email",
                    models.BooleanField(
                        default=False, verbose_name="Отображать Email?"
                    ),
                ),
                (
                    "show_last_name",
                    models.BooleanField(
                        default=False, verbose_name="Отображать фамилию?"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Профиль",
                "verbose_name_plural": "Профили",
            },
        ),
    ]
