# Generated by Django 5.0.6 on 2024-07-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilemodel",
            name="link_to_player",
            field=models.CharField(
                default="", max_length=200, verbose_name="Ссылка на плеер"
            ),
        ),
    ]
