# Generated by Django 5.0.6 on 2024-07-10 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user_app", "0002_profilemodel_link_to_player"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profilemodel",
            name="link_to_player",
        ),
    ]
